create extension if not exists "pgcrypto";
create table if not exists agents (id uuid primary key default gen_random_uuid(), email text unique not null, name text not null, phone text, role text check (role in ('Admin','Manager','Agent')), password_hash text not null, status text default 'active', last_login timestamptz, created_at timestamptz default now());
create table if not exists leads (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, id_number text, dob date, marital_status text, marriage_type text, spouse_details jsonb, phone text, email text, address text, city text, province text, postal_code text, employer_name text, employment_type text, gross_salary numeric, net_salary numeric, additional_income numeric, total_income numeric, salary_date int, bank_name text, branch_code text, account_number text, account_type text, account_holder text, status text default 'new', products jsonb default '[]'::jsonb, created_at timestamptz default now());
create table if not exists clients (id uuid primary key default gen_random_uuid(), lead_id uuid references leads(id) on delete cascade, first_name text, last_name text, status text default 'active', products jsonb default '[]'::jsonb, created_at timestamptz default now());
insert into agents (email, name, role, password_hash, status) values ('admin@creditconsultants.co.za','Admin User','Admin', encode(digest('Admin123!','sha256'),'hex'), 'active') on conflict (email) do nothing;
alter table agents enable row level security; alter table leads enable row level security; alter table clients enable row level security;
drop policy if exists "Allow all" on agents; create policy "Allow all" on agents for all using (true) with check (true);
drop policy if exists "Allow all" on leads; create policy "Allow all" on leads for all using (true) with check (true);
drop policy if exists "Allow all" on clients; create policy "Allow all" on clients for all using (true) with check (true);
